openapi: "3.0.0"
info:
  version: 1.0.0
  title: Simple accountizing
  license:
    name: MIT
servers:
  - url: http://localhost:8088/
paths:
  /accounts:
    get:
      summary: List all accounts
      operationId: listAccounts
      tags:
        - accounts         
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of accounts
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Accounts"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a account
      operationId: createAccount
      tags:
        - accounts
      requestBody:
        $ref: '#/components/requestBodies/AccountBody'
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /accounts/{accountId}:
    get:
      summary: Info for a specific account
      operationId: showAccountById
      tags:
        - accounts
      parameters:
        - name: accountId
          in: path
          required: true
          description: The id of the account to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Account:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
    Accounts:
      type: array
      items:
        $ref: "#/components/schemas/Account"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  parameters:        
    X-Request-ID:
      name: X-Request-ID
      in: header
      description: >-
        ID of the request, unique to the call, as determined by the initiating
        party.
      required: true
      example: 99391c7e-ad88-49ec-a2ad-99ddcb1f7721
      schema:
        type: string
        format: uuid
  requestBodies:
    AccountBody:
      description: A JSON object containing account information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Account'        
  headers:
    X-Request-ID:
      description: >-
        ID of the request, unique to the call, as determined by the initiating
        party.
      required: true
      example: 99391c7e-ad88-49ec-a2ad-99ddcb1f7721
      schema:
        type: string
        format: uuid
 
        
          